### ISSUE TITLE
Update touchscreen firmware

### ISSUE THREAD

**Issue by thesprintster** [realme-kernel-opensource/realmeQ_realme5Pro-kernel-source#1]
I have compiled kernel here in [my repo](https://github.com/thesprintster/kernel_realme_RMX1971)  .

It booted but touch is not working at all.
I suspect touch firmware got updated in new OTA but this kernel has old sources.

Please update it!

**Comment by azharsalim135** [comment]
yeah plz fix it

**Comment by jayeshmann** [comment]
Fix required urgent

**Comment by donv76** [comment]
Yes, please update it

**Comment by MephistoPheles666** [comment]
Yes please update

**Comment by UnparallelSKY** [comment]
Update plox

**Comment by preettamkr** [comment]
@realme please update the kernel source

**Comment by rik9564** [comment]
Plz update the kernel source it is a hectic to make the custom ROMs.......  @realme

**Comment by khofidar94** [comment]
@realme please update kernel source , oh realme ,..

**Comment by Josegamesall** [comment]
Please @realme we need it :(

**Comment by TmvJosue** [comment]
Please @realme-kernel-opensource inspect the problem with the tocuscreen driver/firmware.

**Comment by arijalnp** [comment]
@realme please

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    

hi,sir:pls try the new commit about this.                



    On 10/28/2019 22:25，Josegamesall<notifications@github.com> wrote： 


Please @realme we need it :(

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    


hi,sirpls try the new commit about this.



    On 10/29/2019 16:19，TmvJosue<notifications@github.com> wrote： 


Please @realme-kernel-opensource inspect the problem with the tocuscreen driver/firmware.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    
hi,sirpls try the new commit about this.                



    On 10/30/2019 00:51，khofidar94<notifications@github.com> wrote： 


not any respons fron realme ? ..

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by realme-kernel-opensource** [comment]
font{
        line-height: 1.7;
    }


    


hi,sirpls try the new commit about this.                



    On 10/30/2019 04:20，arijalnp<notifications@github.com> wrote： 


@realme please

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.


        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }

**Comment by jayeshmann** [comment]
@thesprintster source code okay now??

**Comment by thesprintster** [comment]
Yes touch works now, appreciate the response @realme-kernel-opensource
